### ISSUE TITLE
Schedule Section Column

### ISSUE THREAD

**Issue by krjordan** [Just-Develop/Rising-Sun#5]
The schedule section breaks in Firefox. I originally had the schedule as a table, but it added a horizontal scroll to the page on mobile devices if I'm remember correctly. To fix this, I believe bootstrap added the class `.table` to the `<table>`. However, this also breaks in Firefox and the fix that is recommended didn't work for me.

**Comment by shehanmj** [comment]
There is a table-responsive class that should help on mobile devices. 

-----Original Message-----

**Comment by krjordan** [comment]
I actually just figured it out about ten minutes ago. Apparently font-size of 14px breaks the one column (too much text?), but I brought the font-size down to 13px and added 1px of letter-spacing. It works in all other browsers and now in firefox. Push your code to a different branch and I'll do the same that way we can compare and see which one looks better.

**Comment by krjordan** [comment]
Better yet, what I think I'll do is split the adult class into two classes. One for the Tues-Thurs and one for the Sunday. That way I can bump the font size back up without breaking it.

**Comment by shehanmj** [comment]
I figured out my prob with commit. My email was wrong on command git, got it fixed. Got more work and will commit fork and commit tonight. Also trying to get teamviewer pair program it will work with yours too. Haven't really found any other good ones

-----Original Message-----
